### ISSUE TITLE
Log identity should map 1:1 to the origin line

### ISSUE THREAD

**Issue by FiloSottile** [transparency-dev/formats#22]
Currently, a log's default identity if a function of both the log's origin line and the log's key.

https://github.com/transparency-dev/formats/blob/197e4831e3f92099a846631048b54c240cd5153b/log/identifier.go#L22-L33

This has two undesirable properties: it makes key rotation (or a log having multiple keys) awkward at best, and it makes it possible for dishonest logs with the same origin line to rebind signatures.

**Key rotation.** It might be desirable to rotate a log's key, either due to compromise, due to improving security properties of the key storage method, or to migrate to post-quantum algorithms. If the log's identity is independent of the log's key, it would be possible to have transition periods where both keys are accepted, and we'd avoid the awkward situation where post-rotation the log's identity is a hash of an old key. (If you squint, you can also see how the log's key is really an ACL key for witness submission: updating the log's key known to the witnesses might protect even clients that didn't update, because tree heads signed with the old key would not be witnessed. This makes it particularly appealing not to tie logs to their keys.)

**Signature rebinding.** Imagine two logs, A and B, get added to a witness with two different keys *but with the same origin line*. A is a well-known log with monitors and clients, B is unused and unmonitored. A and B grow together until one day a leaf is added to B but not to A. The B tree head is witnessed and signed. A's monitors will never learn about the leaf because they don't monitor B. The problem is that the witness signature over the tree head is also a valid witness signature for A + malicious leaf. This because the witness signed a more general statement than what it actually did: it signed "the log with origin line X had this consistent tree head at size N" when actually it checked that "the log with origin line X **and key K** had this consistent tree head at size N". To make the signed statement match the observed condition, there should be no two logs with the same origin line, so the origin line should be the log's identity.

The main downside is dealing with conflicts. **I suggest a norm is established of making origin lines start with a DNS name and look like a scheme-less URL**, like `example.com/log42`. This doesn't need to be enforced, as long as it gives a clear way for new logs to avoid conflicting with existing logs, so it can be backwards compatible with existing logs (which don't have overlapping origin lines so far). Down the line, if log addition needs to be scaled, it also allows automated anti-spam checks in the form of HTTPS requests to paths derived from the origin line.

This was also discussed on the Sigsum issue tracker more at length, including worked out scenarios for key rotation in case of compromise or algorithm upgrade. https://git.glasklar.is/sigsum/project/documentation/-/issues/26

/cc @AlCutter @mhutchinson

**Comment by mhutchinson** [comment]
Thanks for the writeup @FiloSottile. This is pretty convincing. The work required here is:
- [ ] update the function you referenced to consider only the Origin (#15 v2, essentially)
- [ ] update transparency-dev/witness to use the latest version of this repo
- [ ] all witnesses to update their binaries to the latest version built from the above
- [ ] @AlCutter and I need to update our distributors 

This will be a wild ride of breaking changes, but better sooner than later.
